version: '3.8'

services:
  frontend:
    image: nginx-frontend
    build: 
      context: ./frontend
      args:
        - REACT_APP_SERVICES_HOST=/services/m
    ports:
      - "80:80"
    networks: 
      - demo
  
  backend:
    image: nginx-backend
    build:
      context: ./backend
    networks: 
      - demo

networks: 
  demo: