version: '3.8'

services:
  frontend:
    image: nginx-frontend
    build: 
      context: ./frontend
      args:
        - REACT_APP_SERVICES_HOST=/services/m
    ports:
      - "443:443"
    networks: 
      - demo
    volumes:
      - /etc/ssl/private/nginx.key:/etc/ssl/private/nginx.key
      - /etc/ssl/certs/nginx.crt:/etc/ssl/certs/nginx.crt
  
  backend:
    image: nginx-backend
    build:
      context: ./backend
    networks: 
      - demo

networks: 
  demo: